[workspace]
resolver = "2"
members = [
    "crates/app-core",
    "crates/app",
    "crates/cli",
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.metadata.crane]
name = "melaffeine"

[workspace.dependencies]
app-core = { path = "crates/app-core" }
rustix = { version = "1.1", features = ["process"] }
objc2 = "0.6.3"
block2 = "0.6.2"
objc2-foundation = "0.3.2"
objc2-app-kit = "0.3.2"
objc2-io-kit = "0.3.2"
objc2-core-foundation = "0.3.2"
clap = { version = "4.5", features = ["derive"] }

[workspace.lints.rust]
rust_2018_idioms = { level = "deny", priority = -1 }
rust_2021_compatibility = { level = "deny", priority = -1 }
rust_2024_compatibility = { level = "deny", priority = -1 }
future_incompatible = { level = "deny", priority = -1 }
nonstandard_style = "deny"

[workspace.lints.clippy]
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
style = { level = "deny", priority = -1 }
complexity = { level = "deny", priority = -1 }
perf = { level = "deny", priority = -1 }
missing_errors_doc = "allow"
missing_panics_doc = "allow"
unwrap_used = "deny"
expect_used = "deny"
indexing_slicing = "deny"
arithmetic_side_effects = "deny"
unreachable = "deny"
unimplemented = "deny"
unchecked_time_subtraction = "deny"
todo = "deny"
string_slice = "deny"
panic_in_result_fn = "deny"
panic = "deny"
exit = "deny"
as_conversions = "deny"
manual_let_else = "deny"
uninlined_format_args = "deny"
match_like_matches_macro = "deny"
manual_string_new = "deny"
manual_range_contains = "deny"
manual_flatten = "deny"
manual_filter_map = "deny"
manual_find_map = "deny"
use_self = "deny"
redundant_closure_for_method_calls = "deny"
explicit_into_iter_loop = "deny"
explicit_iter_loop = "deny"
semicolon_if_nothing_returned = "deny"
needless_borrow = "deny"
needless_borrows_for_generic_args = "deny"

[profile.dev]
opt-level = 0
debug = 2

[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
strip = true
