[package]
name = "app"
version.workspace = true
edition.workspace = true

[lib]
name = "app"
path = "src/lib.rs"

[[bin]]
name = "Melaffeine"
path = "src/main.rs"

[dependencies]
app-core.workspace = true
objc2.workspace = true
block2.workspace = true
dispatch2.workspace = true
objc2-foundation = { workspace = true, features = [
    "NSArray",
    "NSDate",
    "NSDateFormatter",
    "NSProcessInfo",
    "NSRunLoop",
    "NSString",
    "NSTimer",
    "block2",
] }
objc2-app-kit = { workspace = true, features = [
    "NSAppearance",
    "NSApplication",
    "NSBitmapImageRep",
    "NSButton",
    "NSColor",
    "NSControl",
    "NSEvent",
    "NSGraphics",
    "NSImage",
    "NSImageRep",
    "NSMenu",
    "NSPopover",
    "NSPopUpButton",
    "NSResponder",
    "NSRunningApplication",
    "NSStatusBar",
    "NSStatusBarButton",
    "NSStatusItem",
    "NSTextField",
    "NSView",
    "NSViewController",
    "NSWindow",
    "block2",
] }
objc2-io-kit = { workspace = true, features = ["pwr_mgt"] }
objc2-core-foundation = { workspace = true, features = ["CFString"] }

[lints]
workspace = true

[[test]]
name = "main_thread_app"
harness = false
